### ISSUE TITLE
first word in the dictionary

### ISSUE THREAD

**Issue by ridicule777** [emerinohdz/FaceBrute#1]
It tries the first word from the dictionary file and reports it as the password.

------
[*] Account to crack : blah@gmail.com
 [*] Loaded : 24422 passwords
 [*] Cracking, please wait ...
[*] trying $@m33r04.. 

 [*] Password found .. !!

 [*] Password : $@m33r04
------

Shuffled the dictionary contents and tried again but it still would report the first word as the password.

**Comment by emerinohdz** [comment]
Hello, this is not mantained anymore, it seems many things have changed since I did this. Regards.
